### ISSUE TITLE
Practica 2. Compuertas lógicas

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/compuertas-logicas-equipo-julio-cesar-gonzalez-lopez#1]
[COMPUERTAS LOGICAS.pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-julio-cesar-gonzalez-lopez/files/7729581/COMPUERTAS.LOGICAS.pdf)

**Comment by RichiMB** [comment]
Portada: 25% cumple con todo.
Procedimiento: 25%, cumple con lo solicitado.
Figuras ilustraciones y fotografías: 25% tiene buena cantidad de imágenes y ayudan a la explicación de los pasos .
Resultados y conclusiones: 25% buenas conclusiones y resultados.

calificacion = 100/100 = 30/30
Calificado por = José Ricardo Mendez Barrios

**Comment by josealfredo79** [comment]
Bien hecho y revisado
